### ISSUE TITLE
Empty response when listing subscriptions throws a KeyError

### ISSUE THREAD

**Issue by lion7** [allenporter/python-google-nest-sdm#1134]
After running into the same error as https://github.com/home-assistant/core/issues/130174, I drilled down to this library.
An empty response can be returned when listing subscriptions, for which the fix probably is similar to https://github.com/allenporter/python-google-nest-sdm/pull/1133. 

My home assistant is running version 2024.11.1, which uses version [6.1.4](https://github.com/home-assistant/core/blob/2024.11.1/requirements_all.txt#L1014) of this library.

**Comment by allenporter** [comment]
Released in https://github.com/allenporter/python-google-nest-sdm/releases/tag/6.1.5
