### ISSUE TITLE
Declare missing dependency: PyYaml

### ISSUE THREAD

**Issue by ncouture** [allenporter/python-google-nest-sdm#286]
`pip install git+https://github.com/allenporter/python-google-nest-sdm` does not install PyYaml.

**Comment by ncouture** [comment]
`pip install google-nest-sdm` does not install PyYaml.

**Comment by allenporter** [comment]
Looks like the yaml dependency was added in the command line tool that ships as part of the library in https://github.com/allenporter/python-google-nest-sdm/pull/3

One angle to consider is that this is "just" for the command line tool so its kind of a shame to introduce the dependency for the common case of packaging this as a library, but that said pyyaml is a common dependency.

 Anyway, i'll send a PR to fix.
