### ISSUE TITLE
Allow to fetch higher resolution images for events

### ISSUE THREAD

**Issue by michaelarnauts** [allenporter/python-google-nest-sdm#52]
Currently, the images that are fetched with `sdm.devices.commands.CameraEventImage.GenerateImage` are 480x360 pixels. Since I want to do some local face recognition (without a Nest Aware subscription), i would like to have some larger images. This is possible by passing the `width` or `height` parameters, but this doesn't seem possible at the moment, and the defaults are used.

I'm not sure how to allow passing this from Home Assistant, or maybe we can just use a better default like 1080p?

Related commit: https://github.com/allenporter/python-google-nest-sdm/commit/170bf1161c01986f53814de74b8898c62ac2ead3

Related PR: https://github.com/home-assistant/core/pull/44638

**Comment by allenporter** [comment]
Hi,

The API for this from Google is described here https://developers.google.com/nest/device-access/api/camera#download_a_camera_image

This is supported.by python-google-nest-sdm here ehm fetching the event image:

https://github.com/allenporter/python-google-nest-sdm/blob/72eb6e7f2464856623e849ad27f2906a0e234d81/google_nest_sdm/camera_traits.py#L187

But I think you're asking for a home assistant feature request. There is an open PR https://github.com/home-assistant/core/pull/53835 but it's not super simple to add this, so thinking through the options as I left in a comment.

Using a better default could be a simple option, which would be a home assistant change to just pass in parameters to those functions.

**Comment by michaelarnauts** [comment]
Ow, I was only looking at the original commit, didn't notice that it has been extended in the meantime. Also, interesting that a related PR is currently being worked on :)

Another solution might be to allow a service call to fetch the actual image (or store it do disk so it's compatible with the camera.snapshot) by passing the eventId (and optionally passing the width/height). This way, I don't need to use the camera.snapshot, but I make another call with the eventId. This would also help with a race condition when multiple events are happening quickly after each other.

**Comment by allenporter** [comment]
We ended up deciding not to go with a separate entity service, however, I am going to make home assistant start capturing images and persisting them to disk by default. I can increase the default resolution as part of that work.

**Comment by michaelarnauts** [comment]
> We ended up deciding not to go with a separate entity service, however, I am going to make home assistant start capturing images and persisting them to disk by default. I can increase the default resolution as part of that work.

Not really sure if this is a good idea. Nest can provide a lot of events (person detected, motion detected), and this can cause a lot of files to be downloaded to disk, while you maybe only want to send a notification with the event image when a person has been detected, and don't want to start worrying about cleaning up the disk.

**Comment by allenporter** [comment]
Agreed it would be very hostile to fill a disk. It will be bounded, and you can also turn it off.

There is also a rest API where you can fetch the media yourself.

**Comment by michaelarnauts** [comment]
> Agreed it would be very hostile to fill a disk. It will be bounded, and you can also turn it off.
> 
> There is also a rest API where you can fetch the media yourself.

A REST API to Nest, or to Home Assistant? If to the Nest API, we also need to do the authentication ourselves, while the integration already has valid tokens.

Can you indicate what the issue is with an additional service call that can do this?

**Comment by allenporter** [comment]
Home assistant rest API, same as the existing camera image API path.

The primary reason is about having so many ways to do the same thing. If we're writing them to disk and exposing a rest API already then we don't also need a service.

**Comment by sunnysyed** [comment]
@allenporter I tried to use the rest API to retrieve the picture and I am able to specify the width and get the proper image size back. However, when an event occurs the image that is returned is still the default 480 size. Is there a force grab a new image using the rest API instead of using the event image?

```camera_proxy/camera.front_door?width=1280```

**Comment by allenporter** [comment]
What size do you want?

The problem is the events have a short window to grab, and so now we're just always going to grab them and persist them to disk in the media player in the next home assistant release -- always for everyone.

So i think what i want to do is just grab a 1600x1600 for everyone to use, then have ?width for downsizing back to a smaller thumbnail for rendering in the grid.

**Comment by sunnysyed** [comment]
I would say 1600 would be ideal. But I guess the other issue now I am seeing is during the 30 second window after the event is the idea to always return the snapshot when requesting a new snapshot? Maybe its better to expose a separate service to get a single frame from rstp stream.  For my use case I wanna wait a few second before grabbing a snapshot to have a better chance at facial recognition in the hopes that the person has walked closer to the door in that time frame.

**Comment by allenporter** [comment]
Yeah, i think what we can do is:
- Document the behavior of the new "event" based API that the media player uses
- Revert behavior of overriding the live stream, restoring behavior fo the camera snapshot to always fetch live

**Comment by sunnysyed** [comment]
@allenporter Any idea when this behavior will be added?

**Comment by allenporter** [comment]
Hi, I think we can likely resolve this in the next home assistant release. 
For context, i've been working on getting the `Media Player` into good shape, and supporting automatic content fetching on events. That is, all events are being fetched automatically from the API and saved to disk. 

As a next step, i plan to increase the snapshot size and document all the APIs for fetching media.

**Comment by allenporter** [comment]
OK, we now fetch 1600x by default on all images and persist them to disk in the media player. Next step I think is to add better documentation to the media player content fetching APIs.

Basically the two APIs are:
"/api/nest/event_media/{device_id}/{event_token}"
"/api/nest/event_media/{device_id}/{event_token}/thumbnail"
and you can see the code here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/nest/__init__.py

I'll update this in the home assistant user facing documentation next, but will consider this item closed.

**Comment by allenporter** [comment]
Hi, check out https://next.home-assistant.io/integrations/nest/#media-attachments and you can use those APIs in the beta for home assistant releasing today i think.

**Comment by sunnysyed** [comment]
Hey,

Sweet yeah I have the dev branch running from a few days ago and is
successfully able to pull in the images. Great work! Now just need to fix
the microsoft face recognition component to allow newer recognition models
and detection models for people with masks on.

Sunny
